module.exports = {
    extends: ['eslint:all', 'prettier'],
    rules: {
        'one-var': ['error', 'never'],
        'no-magic-numbers': 'off',
        'sort-keys': 'off',
        'sort-imports': 'off',
        'max-lines-per-function': 'off',
        'max-statements': 'off',
        'max-lines': 'off',
        'max-params': 'off',
        'max-classes-per-file': 'off',
        'id-length': 'off',
        'no-warning-comments': 'off',
        'no-ternary': 'off',
        'no-continue': 'off',
        'no-undefined': 'off',
        'no-await-in-loop': 'off',
        'no-plusplus': 'off',
        'no-useless-constructor': 'off',
        'new-cap': 'off',
        camelcase: 'off',
        'capitalized-comments': 'off',
        'lines-between-class-members': 'off',
        'require-unicode-regexp': 'off',
        'init-declarations': 'off',
        'multiline-comment-style': 'off',
        'consistent-return': 'off',
        'prefer-named-capture-group': 'off',
        'class-methods-use-this': 'off',
        'no-shadow': 'off',
        'no-empty-function': [
            'error',
            {
                allow: ['arrowFunctions'],
            },
        ],
    },
};
